#cloud-config
hostname: devbox-1
manage_etc_hosts: true
fqdn: devbox-1.jodywan.com
timezone: Europe/London
users:
  - name: centos
    ssh-authorized-keys:
      - ssh-rsa xxxxxx root@pve1
      - ssh-rsa xxxxxx jodywan@Jody-MacBook-Pro.local
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
chpasswd:
  ## Forcing user to change the default password at first login
  expire: true
  list: |
    centos:password
package_upgrade: true
packages:
  - nano
  - vim
  - git
  - ansible-core
